version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build for Prod
          command: npm run build
      
      - run: |
          npm i -g firebase-tools
          firebase deploy --token "${FIREBASE_TOKEN}"


