version: 2
jobs:
  build_and_test:
    docker:
      # specify the version you desire here
      - image: circleci:node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build for Prod
          command: npm run build
      
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "${FIREBASE_TOKEN}"

